/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#e5e2e1",
        "on-error": "#690005",
        "outline-variant": "#444748",
        "on-surface-variant": "#c4c7c8",
        bg: "#000000",
        "on-error-container": "#ffdad6",
        "on-primary": "#2f3131",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-secondary": "#303031",
        "on-tertiary": "#2f3131",
        "on-tertiary-fixed": "#1a1c1c",
        "primary-fixed": "#e2e2e2",
        "on-secondary-fixed-variant": "#464747",
        "surface-container": "#201f1f",
        "on-tertiary-fixed-variant": "#454747",
        "on-surface": "#e5e2e1",
        dim: "#666666",
        "surface-container-highest": "#353434",
        "on-primary-fixed-variant": "#454747",
        "tertiary-container": "#e2e2e2",
        "surface-container-lowest": "#0e0e0e",
        "surface-tint": "#c6c6c7",
        error: "#ffb4ab",
        outline: "#8e9192",
        background: "#141313",
        focus: "#ffffff",
        "surface-container-high": "#2a2a2a",
        "secondary-container": "#464747",
        "on-secondary-container": "#b6b5b5",
        primary: "#ffffff",
        fg: "#ffffff",
        "primary-container": "#e2e2e2",
        "surface-bright": "#3a3939",
        "primary-fixed-dim": "#c6c6c7",
        "on-secondary-fixed": "#1b1c1c",
        "on-tertiary-container": "#636565",
        "tertiary-fixed": "#e2e2e2",
        "surface-container-low": "#1c1b1b",
        surface: "#141313",
        "secondary-fixed-dim": "#c7c6c6",
        "inverse-on-surface": "#313030",
        "error-container": "#93000a",
        "surface-variant": "#353434",
        "secondary-fixed": "#e4e2e2",
        "on-background": "#e5e2e1",
        "on-primary-container": "#636565",
        "inverse-primary": "#5d5f5f",
        secondary: "#c7c6c6",
        tertiary: "#ffffff",
        "on-primary-fixed": "#1a1c1c",
        "surface-dim": "#141313",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        md: "1.5rem",
        xs: "0.5rem",
        unit: "4px",
        gutter: "1rem",
        margin: "2rem",
        lg: "2rem",
        sm: "1rem",
        xl: "4rem",
      },
      fontFamily: {
        "headline-xl": ["Courier New", "Courier", "monospace"],
        "body-base": ["Courier New", "Courier", "monospace"],
        "label-xs": ["Courier New", "Courier", "monospace"],
        "body-sm": ["Courier New", "Courier", "monospace"],
        "headline-lg": ["Courier New", "Courier", "monospace"],
        "space-grotesk": ["Space Grotesk", "sans-serif"],
      },
      fontSize: {
        "headline-xl": [
          "clamp(1.5rem, 4vw, 2.5rem)",
          { lineHeight: "1.1", fontWeight: "700" },
        ],
        "body-base": ["1rem", { lineHeight: "1.5", fontWeight: "400" }],
        "label-xs": ["0.75rem", { lineHeight: "1.2", fontWeight: "400" }],
        "body-sm": ["0.85rem", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-lg": ["1.2rem", { lineHeight: "1.2", fontWeight: "700" }],
      },
      animation: {
        blink: "blink 1s infinite",
      },
      keyframes: {
        blink: {
          "0%, 49%": { opacity: "1" },
          "50%, 100%": { opacity: "0" },
        },
      },
    },
  },
  plugins: [],
};
